/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      width: {
        'sidebar': '165px',
        'sidebar-collapsed': '55px',
        'home-card': '280px',
      },
      height: {
        'quick-launch-sm': '56px',
        'quick-launch-lg': '84px',
      },
      minWidth: {
        'dropdown': '120px',
        'dropdown-lg': '150px',
      },
      minHeight: {
        'skeleton': '40px',
        'moyu-card': '300px',
        'quick-launch': '300px',
      },
      maxWidth: {
        'truncate-sm': '100px',
        'truncate': '120px',
        'truncate-md': '150px',
        'truncate-lg': '180px',
        'truncate-xl': '200px',
      },
      maxHeight: {
        'todo-card': '220px',
        'exchange-history': '300px',
      },
      fontSize: {
        '2xs': ['10px', { lineHeight: '12px' }],
        '3xs': ['9px', { lineHeight: '11px' }],
        '4xs': ['8px', { lineHeight: '10px' }],
        'xs-plus': ['11px', { lineHeight: '14px' }],
      },
      spacing: {
        '3.5': '14px',
        '4.5': '18px',
      },
      backgroundImage: {
        'gradient-primary': 'var(--gradient-primary)',
        'gradient-secondary': 'var(--gradient-secondary)',
        'gradient-login': 'var(--gradient-login)',
        'gradient-login-dark': 'var(--gradient-login-dark)',
        'gradient-button': 'var(--gradient-button)',
        'gradient-float': 'var(--gradient-float)',
      },
      colors: {
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        secondary: 'var(--color-secondary)',
        'secondary-hover': 'var(--color-secondary-hover)',
        accent: 'var(--color-accent)',
        'accent-hover': 'var(--color-accent-hover)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        error: 'var(--color-error)',
        info: 'var(--color-info)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'bg-primary': 'var(--color-bg-primary)',
        'bg-secondary': 'var(--color-bg-secondary)',
        'bg-tertiary': 'var(--color-bg-tertiary)',
        border: 'var(--color-border)',
        'border-light': 'var(--color-border-light)',
        card: 'var(--color-card)',
        'card-hover': 'var(--color-card-hover)',
        sidebar: 'var(--color-sidebar)',
        'sidebar-item': 'var(--color-sidebar-item)',
        'sidebar-item-active': 'var(--color-sidebar-item-active)',
        'button-text': 'var(--color-bg-primary)',
        'todo-1': 'var(--color-todo-1)',
        'todo-2': 'var(--color-todo-2)',
        'todo-3': 'var(--color-todo-3)',
        'todo-4': 'var(--color-todo-4)',
        'todo-5': 'var(--color-todo-5)',
        'todo-6': 'var(--color-todo-6)',
        'todo-7': 'var(--color-todo-7)',
        'todo-8': 'var(--color-todo-8)',
      },
      boxShadow: {
        'primary': 'var(--shadow-primary)',
        'primary-hover': 'var(--shadow-primary-hover)',
        'login': 'var(--shadow-login)',
        'float': 'var(--shadow-float)',
      },
      blur: {
        'sm': 'var(--blur-sm)',
        'md': 'var(--blur-md)',
        'lg': 'var(--blur-lg)',
      },
    },
  },
  plugins: [],
}