import { ShortcutItem } from '../types/settings';

export const AVAILABLE_ICONS = [
  { name: 'Home', label: '主页' },
  { name: 'Wrench', label: '工具' },
  { name: 'Zap', label: '闪电' },
  { name: 'Bookmark', label: '收藏' },
  { name: 'CheckCircle', label: '勾选' },
  { name: 'Search', label: '搜索' },
  { name: 'Flame', label: '火焰' },
  { name: 'Settings', label: '设置' },
  { name: 'FileText', label: '文档' },
  { name: 'Calculator', label: '计算' },
  { name: 'Globe', label: '地球' },
  { name: 'Clipboard', label: '剪贴板' },
  { name: 'MessageSquare', label: '消息' },
  { name: 'Download', label: '下载' },
  { name: 'Upload', label: '上传' },
  { name: 'Camera', label: '相机' },
  { name: 'Music', label: '音乐' },
  { name: 'Image', label: '图片' },
  { name: 'Video', label: '视频' },
  { name: 'Clock', label: '时钟' },
  { name: 'Shield', label: '盾牌' },
  { name: 'Heart', label: '爱心' },
  { name: 'Star', label: '星星' },
  { name: 'User', label: '用户' },
  { name: 'Mail', label: '邮件' },
  { name: 'Phone', label: '电话' },
  { name: 'Map', label: '地图' },
  { name: 'Layers', label: '图层' },
  { name: 'Palette', label: '调色板' },
  { name: 'Bell', label: '铃铛' },
  { name: 'Gift', label: '礼物' },
  { name: 'RefreshCw', label: '刷新' },
  { name: 'Trash2', label: '删除' },
  { name: 'Lock', label: '锁定' },
  { name: 'Unlock', label: '解锁' },
  { name: 'Wifi', label: 'WiFi' },
  { name: 'Battery', label: '电池' },
  { name: 'Volume2', label: '音量' },
  { name: 'VolumeX', label: '静音' },
  { name: 'Maximize2', label: '最大化' },
  { name: 'Minimize2', label: '最小化' },
  { name: 'RotateCcw', label: '旋转' },
  { name: 'Moon', label: '月亮' },
  { name: 'Sun', label: '太阳' },
  { name: 'Cpu', label: 'CPU' },
  { name: 'HardDrive', label: '硬盘' },
  { name: 'Monitor', label: '显示器' },
  { name: 'Smartphone', label: '手机' },
  { name: 'Printer', label: '打印机' },
  { name: 'Cloud', label: '云朵' },
  { name: 'CloudRain', label: '雨云' },
  { name: 'CloudSun', label: '晴云' },
  { name: 'CloudMoon', label: '夜云' },
  { name: 'ZapOff', label: '闪电关' },
  { name: 'AlertCircle', label: '警告' },
  { name: 'AlertTriangle', label: '三角警告' },
  { name: 'Info', label: '信息' },
  { name: 'XCircle', label: '错误' },
  { name: 'HelpCircle', label: '帮助' },
  { name: 'Terminal', label: '终端' },
  { name: 'Code', label: '代码' },
  { name: 'GitBranch', label: '分支' },
  { name: 'Github', label: 'GitHub' },
  { name: 'ExternalLink', label: '外链' },
  { name: 'ChevronRight', label: '右箭头' },
  { name: 'ArrowRight', label: '箭头' },
];

export const AVAILABLE_COLORS = [
  '#03a9f4', '#0462df', '#1db954', '#8c9eff', '#bd081c', '#ea4c89', '#333', '#ff4500',
  '#f5a623', '#bc8acf', '#00bcd4', '#e91e63', '#2196f3', '#9c27b0', '#009688', '#ff9800',
  '#795548', '#607d8b', '#e74c3c', '#9b59b6', '#3498db', '#1abc9c', '#2ecc71', '#f39c12',
];

export const NAV_ACTIONS = [
  { action: 'home', label: '主页' },
  { action: 'tools', label: '工具中心' },
  { action: 'quick', label: '快捷启动' },
  { action: 'bookmark', label: '收藏' },
  { action: 'todo', label: '待办' },
  { action: 'search', label: '搜索' },
  { action: 'news', label: '热点' },
  { action: 'settings', label: '设置' },
];

export const SYSTEM_ACTIONS = [
  { action: 'clear-recycle-bin', label: '清空回收站' },
  { action: 'open-my-computer', label: '打开我的电脑' },
  { action: 'shutdown', label: '关机' },
  { action: 'restart', label: '重启' },
  { action: 'restart-app', label: '重启程序' },
];

export const DEFAULT_SHORTCUTS: ShortcutItem[] = [
  { id: 1, tag: '退出软件', cmd: 'CommandOrControl+Q', isOpen: 1, isGlobal: 1 },
  { id: 2, tag: '隐藏/显示 软件窗口', cmd: 'CommandOrControl+H', isOpen: 1, isGlobal: 1 },
  { id: 3, tag: '隐藏/显示 侧边导航', cmd: 'CommandOrControl+B', isOpen: 1, isGlobal: 0 },
  { id: 4, tag: '打开设置', cmd: 'CommandOrControl+S', isOpen: 1, isGlobal: 0 },
  { id: 5, tag: '取消/设置 窗口置顶', cmd: 'CommandOrControl+T', isOpen: 1, isGlobal: 0 },
  { id: 6, tag: '恢复默认窗口', cmd: 'CommandOrControl+O', isOpen: 1, isGlobal: 0 },
  { id: 7, tag: '刷新当前页面', cmd: 'CommandOrControl+R', isOpen: 1, isGlobal: 0 },
  { id: 8, tag: '最小化窗口', cmd: 'CommandOrControl+[', isOpen: 1, isGlobal: 0 },
  { id: 9, tag: '最大化窗口', cmd: 'CommandOrControl+]', isOpen: 1, isGlobal: 0 },
];

export const FLOAT_TYPE_OPTIONS = [
  { type: 'nav' as const, label: '导航' },
  { type: 'tool' as const, label: '工具' },
  { type: 'app' as const, label: '应用' },
  { type: 'system' as const, label: '系统' },
];

export const DEFAULT_WINDOW_SIZE = { width: 1024, height: 800 };
