export const SECOND = 1000;
export const MINUTE = 60 * SECOND;
export const HOUR = 60 * MINUTE;
export const DAY = 24 * HOUR;

export const CACHE_DURATION = {
  SHORT: 5 * MINUTE,
  MEDIUM: 30 * MINUTE,
  LONG: 1 * HOUR,
  WEEK: 7 * DAY,
};

export const API_TIMEOUT = {
  DEFAULT: 10 * SECOND,
  LONG: 30 * SECOND,
};

export const POLLING_INTERVAL = {
  STATUS: 5 * SECOND,
  SYNC: 30 * SECOND,
};

export const RETRY_CONFIG = {
  MAX_RETRIES: 3,
  DELAY: 1 * SECOND,
  BACKOFF_MULTIPLIER: 2,
};

export const STORAGE_LIMITS = {
  MAX_FILE_SIZE: 50 * 1024 * 1024,
  MAX_IMAGES_PER_REQUEST: 10,
};

export const PAGE_SIZE = {
  DEFAULT: 20,
  SEARCH: 10,
  MAX: 100,
};

export const DISPLAY_LIMITS = {
  WEB_QUICK_TOOLS: 8,
  MOBILE_QUICK_TOOLS: 6,
  WEB_SIXTY_SECONDS_NEWS: 5,
  MOBILE_SIXTY_SECONDS_NEWS: 4,
  WEB_IT_NEWS: 6,
  MOBILE_IT_NEWS: 4,
  WEB_TODAY_IN_HISTORY: 5,
  MOBILE_TODAY_IN_HISTORY: 4,
  AI_NEWS: 4,
  FAVORITES: 12,
  RECENT_TOOLS: 10,
  TAGS: 3,
  HOURLY_FORECAST: 24,
  COLOR_PALETTE: 8,
  CHAT_HEADER_LENGTH: 100,
  DATE_SLICE_LENGTH: 10,
  TIME_SLICE_LENGTH: 5,
  DATETIME_SLICE_LENGTH: 16,
};

export const CRYPTO_CONSTANTS = {
  IV_LENGTH: 16,
  MIN_KEY_LENGTH: 16,
  KEY_LENGTH: 32,
};