export const DISPLAY_LIMITS = {
  WEB_QUICK_TOOLS: 8,
  MOBILE_QUICK_TOOLS: 6,
  WEB_SIXTY_SECONDS_NEWS: 5,
  MOBILE_SIXTY_SECONDS_NEWS: 4,
  WEB_IT_NEWS: 6,
  MOBILE_IT_NEWS: 4,
  WEB_TODAY_IN_HISTORY: 5,
  MOBILE_TODAY_IN_HISTORY: 4,
  AI_NEWS: 4,
  FAVORITES: 12,
  RECENT_TOOLS: 10,
  TAGS: 3,
  HOURLY_FORECAST: 24,
  COLOR_PALETTE: 8,
  CHAT_HEADER_LENGTH: 100,
  DATE_SLICE_LENGTH: 10,
  TIME_SLICE_LENGTH: 5,
  DATETIME_SLICE_LENGTH: 16,
};

export const CRYPTO_CONSTANTS = {
  IV_LENGTH: 16,
  MIN_KEY_LENGTH: 16,
  KEY_LENGTH: 32,
};
